# Generated by Django 3.2.8 on 2022-06-08 22:32

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('tontine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MontantSport',
            new_name='MontantAgape',
        ),
        migrations.RenameField(
            model_name='encaissement',
            old_name='echec_sport',
            new_name='echec_agape',
        ),
        migrations.RenameField(
            model_name='encaissement',
            old_name='tontine_sport',
            new_name='tontine_agape',
        ),
        migrations.RenameField(
            model_name='membre',
            old_name='sport',
            new_name='agape',
        ),
        migrations.RenameField(
            model_name='seance',
            old_name='mtechec_sport',
            new_name='mtechec_agape',
        ),
        migrations.RenameField(
            model_name='seance',
            old_name='nbechec_sport',
            new_name='nbechec_agape',
        ),
        migrations.RenameField(
            model_name='seance',
            old_name='total_sport',
            new_name='total_agape',
        ),
    ]
