# Generated by Django 3.2.8 on 2022-06-04 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicetontine',
            name='franchise',
        ),
    ]
