# Generated by Django 3.2.8 on 2022-06-13 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tontine', '0002_auto_20220608_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersementContributionIndividuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_versement', models.DateTimeField()),
                ('montant', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contrib_ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.contributionindividuelle')),
            ],
        ),
    ]
