# Generated by Django 3.2.8 on 2022-05-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0002_auto_20220531_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicetontine',
            name='franchise',
            field=models.DateTimeField(),
        ),
    ]
