# Generated by Django 3.2.8 on 2022-06-01 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0003_alter_exercicetontine_franchise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliseur',
            name='membre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tontine.membre'),
        ),
    ]
