# Generated by Django 3.2.8 on 2022-06-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0003_versementcontributionindividuelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionindividuelle',
            name='date_reglement',
        ),
    ]
