# Generated by Django 3.2.8 on 2022-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0004_remove_contributionindividuelle_date_reglement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
