# Generated by Django 3.2.8 on 2022-06-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pretbank',
            old_name='avaliseur',
            new_name='garantie',
        ),
    ]
